version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=obt
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cat_db
    ports:
      - "1337:5432"
    restart: unless-stopped